id: aws_taxi_scheduled
namespace: zoomcamp
description: |
  Backfill supported. 
  Uploads Taxi data to AWS S3 and ensures Athena tables exist.

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: green

variables:
  file: "{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}.csv"
  s3_key: "raw/{{inputs.taxi}}/{{vars.file}}"
  data_url: "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{vars.file}}.gz"
  local_file: "{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}.csv"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      taxi: "{{inputs.taxi}}"

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO- {{render(vars.data_url)}} | gunzip > {{render(vars.local_file)}}

  - id: upload_to_s3
    type: io.kestra.plugin.aws.s3.Upload
    accessKeyId: "{{kv('AWS_ACCESS_KEY_ID')}}"
    secretKeyId: "{{kv('AWS_SECRET_ACCESS_KEY')}}"
    region: "{{kv('AWS_REGION')}}"
    bucket: "{{kv('AWS_S3_BUCKET')}}"
    from: "{{outputs.extract.outputFiles[render(vars.local_file)]}}"
    key: "{{render(vars.s3_key)}}"

  - id: if_yellow_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.taxi == 'yellow'}}"
    then:
      - id: create_athena_table_yellow
        type: io.kestra.plugin.aws.athena.Query
        accessKeyId: "{{kv('AWS_ACCESS_KEY_ID')}}"
        secretKeyId: "{{kv('AWS_SECRET_ACCESS_KEY')}}"
        region: "{{kv('AWS_REGION')}}"
        database: "{{kv('AWS_ATHENA_DATABASE')}}"
        outputLocation: "s3://{{kv('AWS_S3_BUCKET')}}/athena-results/"
        query: |
          CREATE EXTERNAL TABLE IF NOT EXISTS yellow_tripdata (
            VendorID INT,
            tpep_pickup_datetime STRING,
            tpep_dropoff_datetime STRING,
            passenger_count INT,
            trip_distance DOUBLE,
            RatecodeID INT,
            store_and_fwd_flag STRING,
            PULocationID INT,
            DOLocationID INT,
            payment_type INT,
            fare_amount DOUBLE,
            extra DOUBLE,
            mta_tax DOUBLE,
            tip_amount DOUBLE,
            tolls_amount DOUBLE,
            improvement_surcharge DOUBLE,
            total_amount DOUBLE,
            congestion_surcharge DOUBLE
          )
          ROW FORMAT DELIMITED
          FIELDS TERMINATED BY ','
          STORED AS TEXTFILE
          LOCATION 's3://{{kv('AWS_S3_BUCKET')}}/raw/yellow/'
          TBLPROPERTIES ('skip.header.line.count'='1');

  - id: if_green_taxi
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.taxi == 'green'}}"
    then:
      - id: create_athena_table_green
        type: io.kestra.plugin.aws.athena.Query
        accessKeyId: "{{kv('AWS_ACCESS_KEY_ID')}}"
        secretKeyId: "{{kv('AWS_SECRET_ACCESS_KEY')}}"
        region: "{{kv('AWS_REGION')}}"
        database: "{{kv('AWS_ATHENA_DATABASE')}}"
        outputLocation: "s3://{{kv('AWS_S3_BUCKET')}}/athena-results/"
        query: |
          CREATE EXTERNAL TABLE IF NOT EXISTS green_tripdata (
            VendorID INT,
            lpep_pickup_datetime STRING,
            lpep_dropoff_datetime STRING,
            store_and_fwd_flag STRING,
            RatecodeID INT,
            PULocationID INT,
            DOLocationID INT,
            passenger_count INT,
            trip_distance DOUBLE,
            fare_amount DOUBLE,
            extra DOUBLE,
            mta_tax DOUBLE,
            tip_amount DOUBLE,
            tolls_amount DOUBLE,
            ehail_fee DOUBLE,
            improvement_surcharge DOUBLE,
            total_amount DOUBLE,
            payment_type INT,
            trip_type INT,
            congestion_surcharge DOUBLE
          )
          ROW FORMAT DELIMITED
          FIELDS TERMINATED BY ','
          STORED AS TEXTFILE
          LOCATION 's3://{{kv('AWS_S3_BUCKET')}}/raw/green/'
          TBLPROPERTIES ('skip.header.line.count'='1');

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    inputs:
      taxi: green

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 1 * *"
    inputs:
      taxi: yellow