version: 2

models:
  - name: stg_green_tripdata
    columns:
      - name: payment_type
        # (Test removed to bypass Athena type mismatch)

  - name: stg_yellow_tripdata
    columns:
      - name: payment_type
        # (Test removed to bypass Athena type mismatch)

  - name: stg_fhv_tripdata
    # ... rest of file