version: 2

models:
  - name: stg_green_tripdata
    columns:
      - name: payment_type
        data_tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]  # Fixed: No quotes

  - name: stg_yellow_tripdata
    columns:
      - name: payment_type
        data_tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6]  # Fixed: No quotes

  - name: stg_fhv_tripdata
    description: "Staging model for FHV data 2019"
    columns:
      - name: dispatching_base_num
        data_tests:
          - not_null