version: 2

sources:
  - name: staging
    database: awsdatacatalog
    schema: zoomcamp          
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata    #for Question 6